# This is just a template placeholder docker-compose file. Use relevant sections which are applicable, 
# and feel free to customize.
version: '3.8'

services:
  frontend:
    # Specify the build context for the frontend
    build:
    # Map the host port to the container port
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    # Specify dependencies (if applicable)
      - "3000:3000"
    # Use app network
    networks:
      - app-network
    depends_on:
      - backend

    # Additional options (uncomment and configure as needed):
    
    # Specify environment variables if needed
    # environment:
    
    # Specify volume for live code reloading (optional)
    # volumes:
    
    # Specify the command to run the development server (if different from Dockerfile)
    # command:

  backend:
    # Specify the build context for the backend
    build:
    # Map the host port to the container port
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    
    # Additional options (uncomment and configure as needed):
    
    # Specify environment variables if needed
    # environment:

    # # Use app network
    networks:
      - app-network
    # Specify volume for live code reloading (optional)
    # volumes:
    
    # Specify the command to run the development server (if different from Dockerfile)
    # command:

# Additional components (uncomment and configure as needed):
# Define a custom network (if applicable)
networks:
  app-network:
    driver: bridge

# Define volumes (if applicable)
# volumes:
